apiVersion: batch/v1
kind: Job
metadata:
  name: create-servicemonitor-crd
  namespace: cattle-system
spec:
  template:
    spec:
      containers:
        - name: kubectl
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - >
              kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
      restartPolicy: OnFailure
