agent:
  enabled: true
  podMetadata:
    labels:
      cluster: ubos-edoxo
  config:
    global:
      scrape_interval: 30s
      evaluation_interval: 5m
      external_labels:
        cluster: ubos-edoxo
    remote_write:
      - url: https://prometheus.t4vpcprod.ubos.tech/api/v1/write
        tls_config:
          insecure_skip_verify: true
server:
  enabled: false
alertmanager:
  enabled: false
kube-state-metrics:
  enabled: true
prometheus-node-exporter:
  enabled: true
resources:
  requests:
    memory: 100Mi
    cpu: 50m
  limits:
    memory: 200Mi
    cpu: 100m
