global:
  cattle:
    clusterId: ubos-edoxo

prometheus:
  prometheusSpec:
    replicas: 1
    enableAdminAPI: false
    enableRemoteWriteReceiver: false
    retention: 1h # локальне сховище тільки на 1 годину
    scrapeInterval: 30s # інтервал збирання
    evaluationInterval: 5m # інтервал оцінки правил (але ми вимикаємо rules)
    ruleSelectorNilUsesHelmValues: false
    externalLabels:
      cluster: ubos-edoxo
    remoteWrite:
      - url: https://prometheus.t4vpcprod.ubos.tech/api/v1/write
        tlsConfig:
          insecureSkipVerify: true
    walCompression: true # стискати WAL, щоб зменшити IO

  additionalScrapeConfigs: []
  additionalAlertManagerConfigs: []
  additionalPodMonitors: []
  additionalServiceMonitors: []

alertmanager:
  enabled: false # повністю вимикаємо

grafana:
  enabled: false # повністю вимикаємо

additionalPrometheusRulesMap: {}

prometheusOperator:
  resources:
    requests:
      memory: 100Mi
      cpu: 50m
    limits:
      memory: 200Mi
      cpu: 100m

# Вимкнути самоперевірки і валідатори, якщо вони не потрібні
admissionWebhooks:
  enabled: false

defaultRules:
  create: false

kubeStateMetrics:
  enabled: true # збираємо kube-state-metrics (можна вимкнути, якщо не треба)

nodeExporter:
  enabled: true # збираємо node-level метрики

prometheus-node-exporter:
  resources:
    requests:
      memory: 30Mi
      cpu: 20m
    limits:
      memory: 50Mi
      cpu: 50m
