global:
  cattle:
    clusterId: ubos-edoxo

prometheus:
  prometheusSpec:
    replicas: 1
    mode: Agent
    enableAdminAPI: false
    enableRemoteWriteReceiver: false
    scrapeInterval: 30s
    evaluationInterval: 5m
    ruleSelectorNilUsesHelmValues: false
    externalLabels:
      cluster: ubos-edoxo
    remoteWrite:
      - url: https://prometheus.t4vpcprod.ubos.tech/api/v1/write
        tlsConfig:
          insecureSkipVerify: true
    walCompression: true
    retention: 0h

  additionalScrapeConfigs: []
  additionalAlertManagerConfigs: []
  additionalPodMonitors: []
  additionalServiceMonitors: []

alertmanager:
  enabled: false

grafana:
  enabled: false

additionalPrometheusRulesMap: {}

prometheusOperator:
  resources:
    requests:
      memory: 50Mi
      cpu: 20m
    limits:
      memory: 100Mi
      cpu: 50m

# Вимкнути admission webhooks
admissionWebhooks:
  enabled: false

defaultRules:
  create: false

kubeStateMetrics:
  enabled: true
  resources:
    requests:
      memory: 20Mi
      cpu: 10m
    limits:
      memory: 40Mi
      cpu: 30m

nodeExporter:
  enabled: true

prometheus-node-exporter:
  resources:
    requests:
      memory: 20Mi
      cpu: 10m
    limits:
      memory: 40Mi
      cpu: 30m
