prometheus:
  prometheusSpec:
    serviceMonitorSelector: {}
    podMonitorSelector: {}
    enableAdminAPI: false
    enableRemoteWriteReceiver: false
    remoteWrite:
      - url: https://rancher.t4vpcprod.ubos.tech/k8s/clusters/local/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-prometheus:9090/proxy/api/v1/write
        bearerTokenSecret:
          name: prometheus-remote-writer-secret
          key: bearer_token
        writeRelabelConfigs: []
    replicas: 1
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 200m
