apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: servicemonitors.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
  names:
    plural: servicemonitors
    singular: servicemonitor
    kind: ServiceMonitor
    shortNames:
      - sm
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                selector:
                  type: object
                endpoints:
                  type: array
                  items:
                    type: object
                namespaceSelector:
                  type: object
  conversion:
    strategy: None
